# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.scraper-v2/ui/dialog_data.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Data(object):
    def setupUi(self, Dialog_Data):
        Dialog_Data.setObjectName("Dialog_Data")
        Dialog_Data.resize(911, 442)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_Data)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(parent=Dialog_Data)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_Data)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Data)

    def retranslateUi(self, Dialog_Data):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Data.setWindowTitle(_translate("Dialog_Data", "Dialog"))
