# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.scraper-v2/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet(
            "#MainWindow{\n"
            '  font-family: "Courier New";\n'
            "  background-color: #FFFFFF;\n"
            "}\n"
            "QGroupBox {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  background-color: rgba(248, 249, 250, 1);\n"
            "}\n"
            "QLineEdit {\n"
            "  padding: 4px 0;\n"
            "  border: 1px solid #ced4da;\n"
            "  border-radius: 8px;\n"
            "  margin-left: 8px;\n"
            "  padding-left: 4px;\n"
            "  background-color: #FFFFFF;\n"
            "  color:#212529;\n"
            "}\n"
            "QPlainTextEdit {\n"
            "    background-color: #FFFFFF;\n"
            "  color:#212529;\n"
            "}\n"
            "QLabel {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: rgb(90, 93, 97);\n"
            "}\n"
            "QRadioButton {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: #212529;\n"
            "}\n"
            "QComboBox {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: #212529;\n"
            "}\n"
            "QPushButton {\n"
            "  color: #212529;\n"
            "}\n"
            "\n"
            "QCheckBox{\n"
            "  color: #212529;\n"
            "}\n"
            "QPushButton#runbot_btn {\n"
            "    margin-top: 8px;\n"
            "    border-radius: 8px;\n"
            "    min-height: 24px;\n"
            "    background-color: #FFA500;\n"
            "}\n"
            ""
        )
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.container_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.container_widget.setObjectName("container_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.container_widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.data_select_container = QtWidgets.QWidget(parent=self.container_widget)
        self.data_select_container.setMinimumSize(QtCore.QSize(0, 0))
        self.data_select_container.setObjectName("data_select_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.data_select_container)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 8)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.data_select_layout = QtWidgets.QHBoxLayout()
        self.data_select_layout.setContentsMargins(0, 0, 0, 0)
        self.data_select_layout.setSpacing(0)
        self.data_select_layout.setObjectName("data_select_layout")
        self.data_combobox = QtWidgets.QComboBox(parent=self.data_select_container)
        self.data_combobox.setObjectName("data_combobox")
        self.data_combobox.addItem("")
        self.data_select_layout.addWidget(self.data_combobox)
        self.data_open_btn = QtWidgets.QPushButton(parent=self.data_select_container)
        self.data_open_btn.setObjectName("data_open_btn")
        self.data_select_layout.addWidget(self.data_open_btn)
        self.horizontalLayout_4.addLayout(self.data_select_layout)
        self.verticalLayout_5.addWidget(self.data_select_container)
        self.line = QtWidgets.QFrame(parent=self.container_widget)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.thread_num_container = QtWidgets.QWidget(parent=self.container_widget)
        self.thread_num_container.setObjectName("thread_num_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.thread_num_container)
        self.horizontalLayout.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thread_num_input = QtWidgets.QSpinBox(parent=self.thread_num_container)
        self.thread_num_input.setObjectName("thread_num_input")
        self.horizontalLayout_2.addWidget(self.thread_num_input)
        self.thread_num_label = QtWidgets.QLabel(parent=self.thread_num_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.thread_num_label.setFont(font)
        self.thread_num_label.setStyleSheet("margin: 0;")
        self.thread_num_label.setObjectName("thread_num_label")
        self.horizontalLayout_2.addWidget(self.thread_num_label)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.thread_num_container)
        self.threads_container_layout = QtWidgets.QVBoxLayout()
        self.threads_container_layout.setObjectName("threads_container_layout")
        self.verticalLayout_5.addLayout(self.threads_container_layout)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem)
        self.group_key_container = QtWidgets.QWidget(parent=self.container_widget)
        self.group_key_container.setObjectName("group_key_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_key_container)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.group_key_label = QtWidgets.QLabel(parent=self.group_key_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.group_key_label.setFont(font)
        self.group_key_label.setStyleSheet("margin: 0;")
        self.group_key_label.setObjectName("group_key_label")
        self.verticalLayout_4.addWidget(self.group_key_label)
        self.group_key_input = QtWidgets.QLineEdit(parent=self.group_key_container)
        self.group_key_input.setStyleSheet("margin: 0;\n" "padding-left: 4px;")
        self.group_key_input.setObjectName("group_key_input")
        self.verticalLayout_4.addWidget(self.group_key_input)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.group_key_container)
        self.ignore_group_key_container = QtWidgets.QWidget(
            parent=self.container_widget
        )
        self.ignore_group_key_container.setObjectName("ignore_group_key_container")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ignore_group_key_container)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ignore_group_key_label = QtWidgets.QLabel(
            parent=self.ignore_group_key_container
        )
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.ignore_group_key_label.setFont(font)
        self.ignore_group_key_label.setStyleSheet("margin: 0;")
        self.ignore_group_key_label.setObjectName("ignore_group_key_label")
        self.verticalLayout_9.addWidget(self.ignore_group_key_label)
        self.ignore_group_key_input = QtWidgets.QLineEdit(
            parent=self.ignore_group_key_container
        )
        self.ignore_group_key_input.setStyleSheet("margin: 0;\n" "padding-left: 4px;")
        self.ignore_group_key_input.setObjectName("ignore_group_key_input")
        self.verticalLayout_9.addWidget(self.ignore_group_key_input)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addWidget(self.ignore_group_key_container)
        self.line_2 = QtWidgets.QFrame(parent=self.container_widget)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.runbot_btn = QtWidgets.QPushButton(parent=self.container_widget)
        self.runbot_btn.setObjectName("runbot_btn")
        self.verticalLayout_5.addWidget(self.runbot_btn)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.container_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_combobox.setItemText(0, _translate("MainWindow", "Select table"))
        self.data_open_btn.setText(_translate("MainWindow", "Open"))
        self.thread_num_label.setText(_translate("MainWindow", "Thread nums"))
        self.group_key_label.setText(_translate("MainWindow", "Group keywords"))
        self.ignore_group_key_label.setText(
            _translate("MainWindow", "Ignore group keywords")
        )
        self.runbot_btn.setText(_translate("MainWindow", "Run bot"))
