# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.scraper-v2/ui/thread_container.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThreadContainer(object):
    def setupUi(self, ThreadContainer):
        ThreadContainer.setObjectName("ThreadContainer")
        ThreadContainer.resize(562, 104)
        ThreadContainer.setStyleSheet(
            "#ThreadContainer{\n"
            '  font-family: "Courier New";\n'
            "  background-color: #FFFFFF;\n"
            "}\n"
            "QGroupBox {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  background-color: rgba(248, 249, 250, 1);\n"
            "}\n"
            "QLineEdit {\n"
            "  padding: 4px 0;\n"
            "  border: 1px solid #ced4da;\n"
            "  border-radius: 8px;\n"
            "  margin-left: 8px;\n"
            "  padding-left: 4px;\n"
            "  background-color: #FFFFFF;\n"
            "  color:#212529;\n"
            "}\n"
            "QPlainTextEdit {\n"
            "    background-color: #FFFFFF;\n"
            "  color:#212529;\n"
            "}\n"
            "QLabel {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: rgb(90, 93, 97);\n"
            "}\n"
            "QRadioButton {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: #212529;\n"
            "}\n"
            "QComboBox {\n"
            '  font-family: "Courier New";\n'
            "  font-size: 13px;\n"
            "  color: #212529;\n"
            "}\n"
            "QPushButton {\n"
            "  color: #212529;\n"
            "}\n"
            "\n"
            "QCheckBox{\n"
            "  color: #212529;\n"
            "}"
        )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ThreadContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.thread_name_label = QtWidgets.QLabel(parent=ThreadContainer)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.thread_name_label.setFont(font)
        self.thread_name_label.setStyleSheet("margin: 0;")
        self.thread_name_label.setIndent(0)
        self.thread_name_label.setObjectName("thread_name_label")
        self.verticalLayout.addWidget(self.thread_name_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.select_udd_input = QtWidgets.QLineEdit(parent=ThreadContainer)
        self.select_udd_input.setStyleSheet("margin: 0px 8px;\n" "padding-left: 4px;")
        self.select_udd_input.setObjectName("select_udd_input")
        self.horizontalLayout_3.addWidget(self.select_udd_input)
        self.select_udd_btn = QtWidgets.QPushButton(parent=ThreadContainer)
        self.select_udd_btn.setObjectName("select_udd_btn")
        self.horizontalLayout_3.addWidget(self.select_udd_btn)
        self.launch_browser_btn = QtWidgets.QPushButton(parent=ThreadContainer)
        self.launch_browser_btn.setStyleSheet("m")
        self.launch_browser_btn.setObjectName("launch_browser_btn")
        self.horizontalLayout_3.addWidget(self.launch_browser_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_progress = QtWidgets.QProgressBar(parent=ThreadContainer)
        self.main_progress.setProperty("value", 24)
        self.main_progress.setObjectName("main_progress")
        self.horizontalLayout.addWidget(self.main_progress)
        self.main_progress_label = QtWidgets.QLabel(parent=ThreadContainer)
        self.main_progress_label.setStyleSheet("margin: 0 4px;")
        self.main_progress_label.setObjectName("main_progress_label")
        self.horizontalLayout.addWidget(self.main_progress_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sub_progress = QtWidgets.QProgressBar(parent=ThreadContainer)
        self.sub_progress.setProperty("value", 24)
        self.sub_progress.setObjectName("sub_progress")
        self.horizontalLayout_2.addWidget(self.sub_progress)
        self.sub_progress_label = QtWidgets.QLabel(parent=ThreadContainer)
        self.sub_progress_label.setStyleSheet("margin: 0 4px;")
        self.sub_progress_label.setObjectName("sub_progress_label")
        self.horizontalLayout_2.addWidget(self.sub_progress_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progress_message = QtWidgets.QLabel(parent=ThreadContainer)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.progress_message.setFont(font)
        self.progress_message.setStyleSheet("margin: 0;")
        self.progress_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progress_message.setIndent(0)
        self.progress_message.setObjectName("progress_message")
        self.verticalLayout.addWidget(self.progress_message)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ThreadContainer)
        QtCore.QMetaObject.connectSlotsByName(ThreadContainer)

    def retranslateUi(self, ThreadContainer):
        _translate = QtCore.QCoreApplication.translate
        ThreadContainer.setWindowTitle(_translate("ThreadContainer", "Form"))
        self.thread_name_label.setText(_translate("ThreadContainer", "Thread Num"))
        self.select_udd_btn.setText(_translate("ThreadContainer", "Select udd"))
        self.launch_browser_btn.setText(_translate("ThreadContainer", "Launch"))
        self.main_progress_label.setText(_translate("ThreadContainer", "0/0"))
        self.sub_progress_label.setText(_translate("ThreadContainer", "0/0"))
        self.progress_message.setText(_translate("ThreadContainer", "Progress msg"))
